-- 1. Criação de Sequências
CREATE SEQUENCE IF NOT EXISTS public.registro_financeiro_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS public.usuario_id_seq START WITH 1 INCREMENT BY 1;

-- 2. Tabela Usuario (Base para Pessoa Física e Jurídica)
CREATE TABLE public.usuario (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(80) NOT NULL,
    email character varying(255),
    senha character varying(255),
    telefone character varying(255),
    endereco character varying(255),
    role character varying(255),
    ativo boolean NOT NULL,
    data_cadastro timestamp(6) without time zone,
    data_atualizacao timestamp(6) without time zone,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT usuario_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'GERENTE'::character varying, 'USUARIO'::character varying])::text[])))
);

-- 3. Tabela Pessoa Física
CREATE TABLE public.pessoa_fisica (
    id bigint NOT NULL,
    cpf character varying(255) NOT NULL,
    genero character varying(255),
    CONSTRAINT pessoa_fisica_pkey PRIMARY KEY (id),
    CONSTRAINT pessoa_fisica_cpf_key UNIQUE (cpf),
    CONSTRAINT fk5vo5yyde5imuvkdiej4v4vlcg FOREIGN KEY (id) REFERENCES public.usuario(id),
    CONSTRAINT pessoa_fisica_genero_check CHECK (((genero)::text = ANY ((ARRAY['MASCULINO'::character varying, 'FEMININO'::character varying])::text[])))
);

-- 4. Tabela Pessoa Jurídica
CREATE TABLE public.pessoa_juridica (
    id bigint NOT NULL,
    cnpj character varying(255) NOT NULL,
    CONSTRAINT pessoa_juridica_pkey PRIMARY KEY (id),
    CONSTRAINT pessoa_juridica_cnpj_key UNIQUE (cnpj),
    CONSTRAINT fk2xbyn6x3mspsqbuc5ykqtn5w4 FOREIGN KEY (id) REFERENCES public.usuario(id)
);

-- 5. Tabela Registro Financeiro
CREATE TABLE public.registro_financeiro (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    usuario_id bigint,
    valor numeric(10,2) NOT NULL,
    tipo character varying(255),
    status character varying(255),
    categoria character varying(255),
    descricao character varying(255),
    forma_pagamento character varying(255),
    data_prevista date,
    data_pagamento date,
    CONSTRAINT registro_financeiro_pkey PRIMARY KEY (id),
    CONSTRAINT fka4607kbvyq3hy5oji80f9mku FOREIGN KEY (usuario_id) REFERENCES public.usuario(id),
    CONSTRAINT registro_financeiro_forma_pagamento_check CHECK (((forma_pagamento)::text = ANY ((ARRAY['PIX'::character varying, 'DINHEIRO'::character varying, 'DEBITO'::character varying, 'CREDITO'::character varying, 'TRANSFERENCIA'::character varying, 'BOLETO'::character varying, 'CHEQUE'::character varying, 'DEPOSITO'::character varying])::text[]))),
    CONSTRAINT registro_financeiro_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'PAGO'::character varying, 'ATRASADO'::character varying, 'RECEBIDO'::character varying, 'AGENDADO'::character varying, 'CANCELADO'::character varying])::text[]))),
    CONSTRAINT registro_financeiro_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['RECEITA'::character varying, 'DESPESA'::character varying])::text[])))
);
